version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: hayk5555/reverseproxy
  backend_user:
    build:
      context: ./udagram-api-users
    image: hayk5555/udagram-api-users
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: hayk5555/udagram-api-feed
  frontend:
    build:
      context: ./udagram-frontend
    image: hayk5555/udagram-frontend:local